"""EN commercial + info landing pages. Source: landing-pages-copy.md."""

PAGES = [
    {
        "slug": "yacht-charter-mallorca",
        "kicker": "Private charter · Palma · Club de Mar",
        "title": "Private Yacht Charter Mallorca — Crewed Maiora, 12 Guests | Limitless",
        "description": "Private crewed yacht charter in Mallorca aboard Limitless, a 21.5 m Maiora from Club de Mar, Palma. Up to 12 guests, crew & VAT included. Half-day to multi-day.",
        "h1": "Private yacht charter in Mallorca",
        "lead": "Limitless is a 21.5-metre Maiora, based at Club de Mar in Palma and looked after by a dedicated crew of two. She is a private charter — just your group, your dates and the stretch of coast you feel like — whether that is a half-day swim in the nearest turquoise cove or a week around the Balearics.",
        "sections": [
            (
                "One boat, entirely yours",
                "We only run one yacht, and only ever for one group at a time. That means the day is built around you: your pace, your music, your idea of a good time on the water. Up to 12 guests by day and 7 overnight, with the crew handling the boat, the anchoring, the beach-club reservations and every other detail so you can focus on the people you are with.",
            ),
            (
                "What's included, and what isn't",
                "Every charter includes the crew, cleaning and VAT — no hidden extras bolted on at the end. Catering and beach clubs are arranged on request, and on multi-day trips provisioning, mooring and fuel run through a transparent APA with a running tally. A quick message tells you exactly where you stand before you commit; nothing is held back.",
            ),
            (
                "On board",
                "An outdoor bar with four fridges and an ice maker, a spacious sun deck, a Seabob, paddleboards, snorkel gear, a lily pad and a jet tender, Bose and Sonos sound throughout, air conditioning and smart TVs below. Everything you need for a day on the water is already aboard.",
            ),
        ],
        "cta": "Tell the captain and crew your dates and group size, and you'll get a personal reply — usually within 24 hours — with route ideas and a clear, all-in quote.",
        "wa": "Hi, I'd like to enquire about a private yacht charter on Limitless.",
        "schema": "Service",
        "service_name": "Private yacht charter Mallorca — Maiora Limitless",
        "low": "1700",
        "high": "4000",
        "faq": [
            ("How many guests can Limitless take?", "Up to 12 guests for a day charter and 7 sleeping aboard on multi-day trips."),
            ("Is the crew included?", "Yes — a professional crew of two, plus cleaning and VAT, are included in every charter. Gratuity is never expected."),
            ("Where does Limitless depart from?", "Club de Mar in Palma de Mallorca."),
        ],
        "related": [
            ("day-charter-mallorca/", "Day charter"),
            ("sunset-charter-mallorca/", "Half-day & sunset"),
            ("multi-day-charter-balearics/", "Multi-day"),
            ("maiora-yacht-charter/", "The yacht"),
            ("destinations/", "Destinations"),
        ],
    },
    {
        "slug": "day-charter-mallorca",
        "kicker": "Day charter · Palma · Club de Mar",
        "title": "Day Charter Mallorca — Full-Day Crewed Yacht from Palma | Limitless",
        "description": "Spend a full day on the water in Mallorca aboard a crewed 21.5 m Maiora. Two or three coves, lunch on board, swimming and water toys. Up to 12 guests, from Club de Mar.",
        "h1": "Day charter in Mallorca",
        "lead": "A full day aboard Limitless is the most popular way to see the coast — enough time to reach two or three coves, swim in properly clear water, have lunch on board and be back for a sunset drink at the marina.",
        "sections": [
            (
                "How a day unfolds",
                "You board at Club de Mar in the morning and the crew shapes the route around you and the weather — the sheltered turquoise bays of the southwest for an easy day, or a longer run down to Es Trenc, Sa Dragonera or Cabrera when the forecast is settled. Swim off the platform, take the Seabob and paddleboards out, and let the day slow right down. It is your boat for the day; there is no schedule but your own.",
            ),
            (
                "Lunch and the details",
                "Catering is arranged on request — anything from a relaxed spread to a proper long lunch — or bring your own. The crew handles anchoring, tender runs ashore and any beach-club reservations. Crew, cleaning and VAT are included; you'll have a clear quote before the day.",
            ),
        ],
        "cta": "Send the crew your date and group size for route ideas and an all-in day-charter quote.",
        "wa": "Hi, I'd like to enquire about a day charter on Limitless.",
        "schema": "Service",
        "service_name": "Day charter Mallorca — Maiora Limitless",
        "low": "3000",
        "high": "4000",
        "faq": [
            ("How long is a full-day charter?", "Typically 8–10 hours. Shorter 4- and 6-hour options are on the half-day page."),
            ("Which coves can we reach in a day?", "The southwest bays easily; Es Trenc, Sa Dragonera and Cabrera on settled-weather full days. The crew will advise for your date."),
        ],
        "related": [
            ("sunset-charter-mallorca/", "Half-day & sunset"),
            ("destinations/", "Destinations"),
            ("yacht-charter-mallorca-prices/", "Prices"),
            ("maiora-yacht-charter/", "The yacht"),
        ],
    },
    {
        "slug": "sunset-charter-mallorca",
        "kicker": "Half-day · Sunset · Palma",
        "title": "Half-Day & Sunset Yacht Charter Mallorca | Limitless Palma",
        "description": "A 4- or 6-hour crewed charter from Palma — a morning swim, an afternoon on the water, or a sunset cruise. Aboard a 21.5 m Maiora, up to 12 guests. Crew & VAT included.",
        "h1": "Half-day and sunset charters",
        "lead": "Not every day on the water needs to be a whole day. A half-day aboard Limitless — four or six hours — is time enough for a morning swim in a nearby cove, a lazy afternoon, or a sunset cruise out of Palma bay with a drink in hand.",
        "sections": [
            (
                "Short, but not rushed",
                "Because our home bays are so close — Portals Vells is barely 35 minutes away — a half-day still buys you real time in the water. A morning charter for a swim and a paddle before lunch; an afternoon that drifts into evening; or a sunset run when the light goes gold over the bay and the coast empties out.",
            ),
            (
                "Included",
                "Crew, cleaning and VAT are part of the price, and the sound system, water toys and outdoor bar are all yours for the session. Drinks and catering on request.",
            ),
        ],
        "cta": "Message the crew with your date and whether you'd like a morning, afternoon or sunset — you'll get a quick, all-in quote.",
        "wa": "Hi, I'd like to enquire about a half-day or sunset charter on Limitless.",
        "schema": "Service",
        "service_name": "Half-day and sunset charter Mallorca — Maiora Limitless",
        "low": "1700",
        "high": "3100",
        "faq": [
            ("How long is a half-day charter?", "Four or six hours — your choice."),
            ("Can we do a sunset cruise?", "Yes — an evening half-day timed for sunset over Palma bay is one of the loveliest ways to use the boat."),
        ],
        "related": [
            ("day-charter-mallorca/", "Full day"),
            ("destinations/portals-vells/", "Portals Vells"),
            ("yacht-charter-mallorca-prices/", "Prices"),
        ],
    },
    {
        "slug": "multi-day-charter-balearics",
        "kicker": "Overnight · Balearics",
        "title": "Multi-Day & Overnight Yacht Charter — Balearics | Limitless Mallorca",
        "description": "Sleep aboard and wake in a new bay — multi-day crewed charters around Mallorca, Menorca, Ibiza and Formentera. 21.5 m Maiora, up to 7 overnight guests, transparent APA.",
        "h1": "Multi-day and overnight charters",
        "lead": "Give it more than a day and Mallorca opens right up — and Menorca, Ibiza and Formentera come within reach. On a multi-day charter you sleep aboard, wake somewhere new each morning, and let the trip find its own rhythm.",
        "sections": [
            (
                "Where you can go",
                "Island-hop the wild Tramuntana coast in the northwest, cross to Formentera's turquoise sandbanks and Ibiza's anchorages, slip over to quiet Menorca, or take the full circumnavigation of Mallorca over five to seven days. Up to 7 guests sleep aboard; the crew builds each day around the weather and what you feel like doing.",
            ),
            (
                "Honest about the costs",
                "Longer trips run through an APA — an advance provisioning allowance, typically around 10% of the charter fee — covering provisions, extra fuel and mooring, with the captain keeping a transparent running tally throughout. Anything left at the end comes back to you. We'd rather over-explain the numbers than surprise you; a quick message gets you a clear breakdown for your dates.",
            ),
        ],
        "cta": "Tell the crew your dates and where you'd love to go — you'll get a realistic route, mileage and cost sketch, nothing held back.",
        "wa": "Hi, I'd like to enquire about a multi-day charter on Limitless.",
        "schema": "Service",
        "service_name": "Multi-day yacht charter Balearics — Maiora Limitless",
        "low": "3000",
        "high": "4000",
        "faq": [
            ("How many guests can sleep aboard?", "Up to 7 overnight."),
            ("What is APA?", "An advance provisioning allowance (around 10% of the charter fee) covering provisions, extra fuel and mooring on multi-day trips, tracked transparently and reconciled at the end."),
        ],
        "related": [
            ("destinations/", "Destinations"),
            ("destinations/ibiza-formentera/", "Ibiza & Formentera"),
            ("destinations/menorca-crossing/", "Menorca"),
            ("what-is-included/", "What's included"),
        ],
    },
    {
        "slug": "maiora-yacht-charter",
        "kicker": "Maiora 21.5 m · Club de Mar",
        "title": 'Maiora 21.5 m Yacht Charter Mallorca — "Limitless" | Crewed, 12 Guests',
        "description": "Charter Limitless, a 21.5 m Maiora flybridge motor yacht at Club de Mar, Palma. Up to 12 day / 7 overnight guests, crew of two, Seabob, jet tender and full water toys.",
        "h1": "Limitless — a 21.5 m Maiora",
        "lead": "Limitless is a Maiora flybridge motor yacht, 21.5 metres of warm, well-kept space built for exactly the kind of days Mallorca does best. She is maintained to charter standard and run by a dedicated crew of two who genuinely love the sea.",
        "sections": [
            (
                "Built for the coast",
                "Twin MTU engines move her comfortably at a cruising 16 knots, so the coves are never far, and there is room to spread out: a generous flybridge and sun deck up top, elegant outdoor seating and an outdoor bar with four fridges and an ice maker aft, and a cool, air-conditioned interior below. She takes up to 12 guests by day and sleeps 7.",
            ),
            (
                "The toys",
                "A 330 jet tender, a Seabob, a stand-up paddleboard, snorkel sets and a lily pad; Bose hi-fi and Sonos control throughout, smart TVs, and a swim ladder and platform that make getting in and out of the water effortless.",
            ),
            (
                "The crew",
                "Two on board who handle everything — catering, beach-club reservations, the anchoring and all the details — attentive and experienced, and part of a small team who share equally in whatever recognition guests choose to give. Gratuity is never expected.",
            ),
            (
                "Yacht at a glance",
                "Builder: Maiora · Length: 21.5 m × 5.6 m beam · Engines: 2 × MTU, 1,500 HP · Guests: 12 day / 7 overnight · Crew: 2 · Home port: Club de Mar, Palma de Mallorca. You will not confuse her with the 96 m Lürssen also named Limitless that sometimes berths in the same marina. This page is the charter yacht.",
            ),
        ],
        "cta": "Message the captain and crew to check dates and get a quote.",
        "wa": "Hi, I'd like to enquire about chartering the Maiora Limitless.",
        "schema": "Product",
        "service_name": "Maiora 21.5 m Limitless yacht charter Mallorca",
        "low": "1700",
        "high": "4000",
        "faq": [],
        "related": [
            ("yacht-charter-mallorca/", "Private charter"),
            ("day-charter-mallorca/", "Day charter"),
            ("yacht-charter-mallorca-prices/", "Prices"),
        ],
    },
    {
        "slug": "yacht-charter-palma-club-de-mar",
        "kicker": "Palma · Club de Mar",
        "title": "Yacht Charter Palma de Mallorca — from Club de Mar | Limitless",
        "description": "Private crewed yacht charter departing Club de Mar in Palma de Mallorca. Step aboard a 21.5 m Maiora minutes from the city and be swimming in a turquoise cove within the hour.",
        "h1": "Yacht charter from Club de Mar, Palma",
        "lead": "Limitless is berthed at Club de Mar, one of Palma's classic marinas, right on the edge of the city and the old town. It means you can be sipping a coffee in Palma one moment and anchored over turquoise water the next — the nearest coves are barely half an hour away.",
        "sections": [
            (
                "A perfect base",
                "From Club de Mar the whole southwest coast is on your doorstep: Portals Vells and its sea caves, the Illes Malgrats marine reserve, the sheltered blue of Cala Llamp — all within an easy morning. Point the other way and the south coast's white-sand beaches and Cabrera's national park open up for a full day. Wherever you start from, the crew meets you at the boat and takes it from there.",
            ),
            (
                "Easy from anywhere in Palma",
                "The marina is a short taxi from anywhere in the city and the cruise-port and airport are close by, which makes Limitless an easy choice whether you are staying in Palma, out at Portals, or just off a flight.",
            ),
        ],
        "cta": "Send your dates and group size to the crew for routes from Club de Mar and a transparent quote.",
        "wa": "Hi, I'd like to enquire about a charter from Club de Mar on Limitless.",
        "schema": "Service",
        "service_name": "Yacht charter from Club de Mar Palma — Maiora Limitless",
        "low": "1700",
        "high": "4000",
        "faq": [],
        "related": [
            ("destinations/portals-vells/", "Portals Vells"),
            ("destinations/", "All destinations"),
            ("day-charter-mallorca/", "Day charter"),
        ],
    },
    {
        "slug": "destinations",
        "kicker": "Routes · Mallorca · Balearics",
        "title": "Where Limitless Takes You — Mallorca Coves & Balearic Routes | Limitless",
        "description": "From the turquoise coves near Palma to Cabrera, Es Trenc, Sa Dragonera and across to Ibiza, Formentera and Menorca — explore every route aboard a crewed 21.5 m Maiora.",
        "h1": "Where Limitless takes you",
        "lead": "Every route is shaped around your group — the destinations below are a starting point, not a fixed menu. Half-day swims in the nearest bays, full days down the coast, or multi-day crossings to the neighbouring islands: tell the crew your dates and what you're after, and you'll get a realistic plan for your trip.",
        "sections": [
            (
                "Close to Palma — half-day coves",
                "The sheltered, turquoise bays of the southwest, all within an easy morning: Portals Vells and its sea caves, the Illes Malgrats marine reserve off El Toro, and the deep, calm blue of Cala Llamp.",
            ),
            (
                "Down the coast — full days",
                "Longer, settled-weather runs to Mallorca's finest beaches and reserves: Sa Dragonera's island wilderness, the dramatic inlet of Cala Pi, the Caribbean sand of Es Trenc, the protected archipelago of Cabrera, and the photographed coves of the southeast.",
            ),
            (
                "Beyond Mallorca — multi-day",
                "Sleep aboard and reach further: the mountainous northwest coast, a full circumnavigation of the island, and crossings to Ibiza and Formentera or quiet Menorca.",
            ),
        ],
        "cta": "Message the captain and crew with your dates — they'll suggest the route that fits.",
        "wa": "Hi, I'd like to enquire about a destination day on Limitless.",
        "schema": "ItemList",
        "service_name": "Yacht charter destinations Mallorca",
        "low": None,
        "high": None,
        "faq": [],
        "hub": True,
        "related": [
            ("day-charter-mallorca/", "Day charter"),
            ("sunset-charter-mallorca/", "Half-day"),
            ("multi-day-charter-balearics/", "Multi-day"),
        ],
    },
    {
        "slug": "yacht-charter-mallorca-prices",
        "kicker": "Rates · Transparent",
        "title": "Yacht Charter Mallorca Prices — Transparent Rates | Limitless",
        "description": "What a crewed yacht charter in Mallorca costs aboard Limitless: half-day from €1,700, full day from €3,000, crew & VAT included. Clear pricing, no hidden extras.",
        "h1": "Yacht charter Mallorca — prices",
        "lead": "We keep pricing simple and out in the open. Below are the starting rates for Limitless; the figures are a guide, and a quick message gets you an exact, all-in quote for your dates with nothing bolted on at the end.",
        "sections": [
            (
                "Charter rates",
                "Low season — half-day (4h) from €1,700 · 6 hours from €2,400 · full day from €3,000. High season (July–August) — half-day (4h) from €2,200 · 6 hours from €3,100 · full day from €4,000. Crew and VAT are included in every rate.",
            ),
            (
                "What's included",
                "Your professional crew of two, cleaning and VAT are all part of the price. Also aboard at no extra cost: the Seabob, jet tender, paddleboards, snorkel gear, sound system and outdoor bar. A refundable security deposit (20%) applies.",
            ),
            (
                "What's extra",
                "Catering and beach-club reservations are arranged on request. On multi-day charters, provisioning, mooring, extra fuel and the final cleaning run through a transparent APA with a running tally. Crew gratuity is never expected — entirely at your discretion.",
            ),
        ],
        "cta": "Send your dates for an exact quote — a clear picture upfront, no commitment.",
        "wa": "Hi, I'd like a quote for a charter on Limitless.",
        "schema": "Service",
        "service_name": "Yacht charter Mallorca prices — Limitless",
        "low": "1700",
        "high": "4000",
        "faq": [
            ("What does a day charter in Mallorca cost?", "Full days start from €3,000 in low season and €4,000 in July–August, crew and VAT included."),
            ("Are there hidden costs?", "No. Crew, cleaning and VAT are included; catering and multi-day running costs are shown transparently before you book."),
        ],
        "related": [
            ("what-is-included/", "What's included"),
            ("best-time-yacht-charter-mallorca/", "Best time to charter"),
            ("day-charter-mallorca/", "Day charter"),
        ],
    },
    {
        "slug": "what-is-included",
        "kicker": "How it works",
        "title": "What's Included & How a Charter Works | Limitless Mallorca",
        "description": "Everything included in a Limitless charter, how the day works, and plain answers on APA, deposits and gratuity. Transparent, crewed yacht charter from Palma de Mallorca.",
        "h1": "What's included, and how it works",
        "lead": "No jargon and no surprises. Here is exactly what you get, how a charter runs, and honest answers to the questions everyone asks.",
        "sections": [
            (
                "Included in every charter",
                "Your crew of two, cleaning and VAT; the full run of water toys (Seabob, jet tender, paddleboards, snorkel sets, lily pad); the sound system, air conditioning and outdoor bar. A refundable 20% security deposit applies.",
            ),
            (
                "How a day works",
                "You board at Club de Mar and the crew shapes the route around you and the weather. Swim, cruise, eat on board, take the tender ashore — there is no schedule but your own. Catering and beach clubs are arranged on request; the crew handles the anchoring and the details throughout.",
            ),
            (
                "APA, explained",
                "On multi-day charters an advance provisioning allowance — typically around 10% of the charter fee — covers provisions, extra fuel and mooring. The captain keeps a transparent running tally, tops it up only if it runs low, and returns any balance at the end. Day charters don't use an APA.",
            ),
            (
                "Gratuity",
                "Never included, never expected. If you'd like to recognise the crew, it is entirely at your discretion — cash, handed to the captain, and shared equally across the team.",
            ),
        ],
        "cta": "Still have a question? Message the captain and crew — they'll answer honestly, usually within 24 hours.",
        "wa": "Hi, I have a question about what's included on a Limitless charter.",
        "schema": "FAQPage",
        "service_name": "What's included — Limitless yacht charter",
        "low": None,
        "high": None,
        "faq": [
            ("What is APA?", "An advance provisioning allowance on multi-day charters (~10% of the fee) covering provisions, fuel and mooring, tracked transparently and reconciled at the end."),
            ("Is gratuity included?", "No, and it is never expected — entirely at your discretion."),
            ("Is there a deposit?", "Yes, a refundable security deposit of 20%."),
        ],
        "related": [
            ("yacht-charter-mallorca-prices/", "Prices"),
            ("multi-day-charter-balearics/", "Multi-day"),
            ("yacht-charter-mallorca/", "Private charter"),
        ],
    },
    {
        "slug": "best-time-yacht-charter-mallorca",
        "kicker": "Season guide",
        "title": "Best Time to Charter a Yacht in Mallorca — Season Guide | Limitless",
        "description": "When to charter in Mallorca: warm calm seas from May to October, quieter shoulder months, and July–August at its liveliest. An honest month-by-month guide from the crew.",
        "h1": "The best time to charter in Mallorca",
        "lead": "Mallorca is a genuinely long season on the water. Here is how the months actually feel from the deck, so you can pick the trip that suits you — and Limitless is available year-round.",
        "sections": [
            (
                "May, June, September, October — the sweet spot",
                "Warm, settled seas and softer light, with the coves far quieter than mid-summer. For many guests these shoulder months are the best of all: the water is swimmable, the anchorages have space, and the longer runs down to Cabrera or across to the islands are easy on calm days. Low-season rates apply.",
            ),
            (
                "July & August — peak summer",
                "The liveliest, warmest months, with the longest days and the busiest coves. It is Mallorca at full tilt — book early, as our calendar fills quickly, and expect high-season rates (July–August).",
            ),
            (
                "A note on the weather",
                "The crew always shapes the day around the forecast — where you go on any given day depends on the wind, and they'll steer you to the most sheltered, beautiful water available. It is why the routes are a starting point, not a fixed plan.",
            ),
        ],
        "cta": "Tell the crew roughly when you'd like to come and they'll tell you honestly what's bookable and what the water is like then.",
        "wa": "Hi, I'd like to check the best dates for a charter on Limitless.",
        "schema": "FAQPage",
        "service_name": "Best time to charter Mallorca",
        "low": None,
        "high": None,
        "faq": [
            ("When is the best time to charter in Mallorca?", "May, June, September and October offer warm, calm, quieter conditions; July and August are the liveliest and busiest."),
            ("Is Limitless available all year?", "Yes — available year-round, with low-season and July–August high-season rates."),
        ],
        "related": [
            ("yacht-charter-mallorca-prices/", "Prices"),
            ("day-charter-mallorca/", "Day charter"),
        ],
    },
]
