"""German copy for commercial landing pages + destination overlays."""

UI = {
    "check_dates": "Termine prüfen",
    "whatsapp": "Crew per WhatsApp schreiben",
    "call": "Anrufen +34 643 678 072",
    "see_calendar": "Kalender ansehen",
    "home": "Startseite",
    "dates": "Termine",
    "legal": "Rechtliches",
    "destinations": "Reiseziele",
    "charters": "Charter",
    "the_yacht": "Die Yacht",
    "prices": "Preise",
    "contact": "Kontakt",
    "private_charter": "Privater Charter",
    "day_charter": "Tagescharter",
    "sunset": "Halbtag & Sonnenuntergang",
    "multi_day": "Mehrtage",
    "club_de_mar": "Club de Mar, Palma",
    "whats_included": "Was inklusive ist",
    "best_time": "Beste Reisezeit",
    "footer_charters": "Charter",
    "footer_info": "Infos",
    "note": "Kapitän und Crew antworten meist innerhalb einer Stunde, immer innerhalb von 24 Stunden. Crew und MwSt. inklusive. Trinkgeld wird nicht erwartet.",
    "facts": "Auf einen Blick",
    "from_marina": "Ab Club de Mar",
    "round_trip": "Hin und zurück",
    "depth": "Tiefe",
    "diesel": "Diesel ca.",
    "trip": "Tour",
    "half-day": "Halbtag",
    "full-day": "Ganztag",
    "multi-day": "Mehrtage",
    "nm": "sm",
    "more_routes": "Weitere Routen",
    "faq": "Häufige Fragen",
}

PAGES = {
    "yacht-charter-mallorca": {
        "kicker": "Privater Charter · Palma · Club de Mar",
        "title": "Yachtcharter Mallorca — Maiora mit Crew, 12 Gäste | Limitless",
        "description": "Privater Yachtcharter auf Mallorca an Bord der Limitless, einer 21,5 m Maiora ab Club de Mar, Palma. Bis 12 Gäste, Crew und MwSt. inklusive. Halbtag bis Mehrtage.",
        "h1": "Yachtcharter Mallorca",
        "lead": "Limitless ist eine 21,5-Meter-Maiora im Club de Mar in Palma, betreut von einer festen Crew aus zwei Personen. Ein privater Charter — nur Ihre Gruppe, Ihre Termine und die Küste, die Sie sehen wollen. Ob ein Halbtag in der nächsten türkisen Bucht oder eine Woche durch die Balearen.",
        "sections": [
            (
                "Ein Boot, ganz für Sie",
                "Wir fahren nur eine Yacht, und immer nur für eine Gruppe. Der Tag richtet sich nach Ihnen: Ihr Tempo, Ihre Musik, Ihre Idee eines guten Tages auf dem Wasser. Tagsüber bis 12 Gäste, über Nacht 7. Die Crew führt das Boot, ankert, reserviert Beach Clubs — Sie konzentrieren sich auf die Menschen, mit denen Sie da sind.",
            ),
            (
                "Was inklusive ist — und was nicht",
                "Jeder Charter enthält Crew, Reinigung und MwSt. — keine versteckten Posten am Ende. Catering und Beach Clubs auf Wunsch. Bei Mehrtagen laufen Verpflegung, Liegeplatz und Kraftstoff über eine transparente APA mit laufender Abrechnung. Eine kurze Nachricht zeigt Ihnen vorher klar, wo Sie stehen.",
            ),
            (
                "An Bord",
                "Outdoor-Bar mit vier Kühlschränken und Eiswürfelbereiter, großes Sonnendeck, Seabob, SUPs, Schnorchelausrüstung, Lily Pad und Jet-Tender, Bose und Sonos, Klimaanlage und Smart-TVs unten. Alles für den Tag auf dem Wasser ist schon an Bord.",
            ),
        ],
        "cta": "Schreiben Sie Kapitän und Crew Termine und Gruppengröße — Sie bekommen meist innerhalb von 24 Stunden eine persönliche Antwort mit Routen und einem klaren Gesamtpreis. Siehe <a href=\"../yacht-charter-mallorca-prices/\">Charterpreise</a>.",
        "wa": "Hallo, ich interessiere mich für einen privaten Yachtcharter auf der Limitless.",
        "service_name": "Yachtcharter Mallorca — Maiora Limitless",
        "faq": [
            ("Wie viele Gäste nimmt die Limitless?", "Tagsüber bis 12 Gäste, über Nacht 7."),
            ("Ist die Crew inklusive?", "Ja — eine professionelle Crew aus zwei Personen, Reinigung und MwSt. gehören zu jedem Charter. Trinkgeld wird nicht erwartet."),
            ("Wo startet die Limitless?", "Club de Mar in Palma de Mallorca."),
        ],
        "related_labels": ["Tagescharter", "Halbtag & Sonnenuntergang", "Mehrtage", "Die Yacht", "Reiseziele"],
    },
    "day-charter-mallorca": {
        "kicker": "Tagescharter · Palma · Club de Mar",
        "title": "Tagescharter Mallorca — Ganztag mit Crew ab Palma | Limitless",
        "description": "Ein ganzer Tag auf dem Wasser vor Mallorca an Bord einer 21,5 m Maiora mit Crew. Zwei oder drei Buchten, Mittagessen an Bord, Schwimmen und Wasserspielzeug. Bis 12 Gäste, ab Club de Mar.",
        "h1": "Tagescharter auf Mallorca",
        "lead": "Ein ganzer Tag auf der Limitless ist der beliebteste Weg, die Küste zu sehen — Zeit für zwei oder drei Buchten, klares Wasser, Mittagessen an Bord und einen Drink bei Sonnenuntergang zurück in der Marina.",
        "sections": [
            (
                "So läuft ein Tag",
                'Sie steigen morgens im Club de Mar zu, die Crew formt die Route nach Ihnen und dem Wetter — die geschützten türkisen Buchten im Südwesten für einen leichten Tag, oder bei ruhigem Wetter weiter nach <a href="../destinations/es-trenc/">Es Trenc</a>, <a href="../destinations/sa-dragonera/">Sa Dragonera</a> oder <a href="../destinations/cabrera/">Cabrera</a>. Schwimmen von der Plattform, Seabob und SUPs, der Tag darf langsam werden. Es ist Ihr Boot; es gibt keinen Plan außer Ihrem.',
            ),
            (
                "Mittagessen und Details",
                "Catering auf Wunsch — vom lockeren Buffet bis zum langen Mittagessen — oder Sie bringen selbst etwas mit. Die Crew ankert, fährt Tender und reserviert Beach Clubs. Crew, Reinigung und MwSt. sind inklusive; Sie haben vorher einen klaren Preis.",
            ),
        ],
        "cta": "Schicken Sie der Crew Termin und Gruppengröße — Sie bekommen Routenideen und einen Gesamtpreis für den Tagescharter. Siehe <a href=\"../yacht-charter-mallorca-prices/\">Charterpreise</a>.",
        "wa": "Hallo, ich interessiere mich für einen Tagescharter auf der Limitless.",
        "service_name": "Tagescharter Mallorca — Maiora Limitless",
        "faq": [
            ("Wie lange dauert ein Ganztagescharter?", "Typisch 8–10 Stunden. Kürzere 4- und 6-Stunden-Optionen stehen auf der Halbtagsseite."),
            ("Welche Buchten erreichen wir an einem Tag?", "Die Südwestbuchten locker; Es Trenc, Sa Dragonera und Cabrera an ruhigen Ganztagen. Die Crew berät zu Ihrem Termin."),
        ],
        "related_labels": ["Halbtag & Sonnenuntergang", "Reiseziele", "Preise", "Die Yacht"],
    },
    "sunset-charter-mallorca": {
        "kicker": "Halbtag · Sonnenuntergang · Palma",
        "title": "Halbtag & Sonnenuntergang Yachtcharter Mallorca | Limitless Palma",
        "description": "4 oder 6 Stunden mit Crew ab Palma — morgens schwimmen, nachmittags auf dem Wasser oder eine Sunset-Fahrt. 21,5 m Maiora, bis 12 Gäste. Crew und MwSt. inklusive.",
        "h1": "Halbtag und Sonnenuntergang",
        "lead": "Nicht jeder Tag auf dem Wasser muss ein ganzer Tag sein. Ein Halbtag auf der Limitless — vier oder sechs Stunden — reicht für ein Morgenbaden in einer nahen Bucht, einen langsamen Nachmittag oder eine Sunset-Fahrt aus der Bucht von Palma mit einem Drink in der Hand.",
        "sections": [
            (
                "Kurz, aber nicht gehetzt",
                'Unsere Heimatbuchten sind nah — <a href="../destinations/portals-vells/">Portals Vells</a> kaum 35 Minuten — deshalb bleibt im Halbtag echte Zeit im Wasser. Morgens schwimmen und paddeln vor dem Mittagessen; ein Nachmittag, der in den Abend gleitet; oder eine Sunset-Fahrt, wenn das Licht über der Bucht gold wird und die Küste leer wird.',
            ),
            (
                "Inklusive",
                "Crew, Reinigung und MwSt. gehören zum Preis. Sound, Wasserspielzeug und Outdoor-Bar sind Ihre für die Session. Getränke und Catering auf Wunsch.",
            ),
        ],
        "cta": "Schreiben Sie der Crew Ihren Termin und ob Sie Morgen, Nachmittag oder Sonnenuntergang wollen — Sie bekommen schnell einen Gesamtpreis. Siehe <a href=\"../yacht-charter-mallorca-prices/\">Charterpreise</a>.",
        "wa": "Hallo, ich interessiere mich für einen Halbtag oder Sunset-Charter auf der Limitless.",
        "service_name": "Halbtag und Sunset-Charter Mallorca — Maiora Limitless",
        "faq": [
            ("Wie lange ist ein Halbtag?", "Vier oder sechs Stunden — Ihre Wahl."),
            ("Geht eine Sunset-Fahrt?", "Ja — ein Abend-Halbtag zum Sonnenuntergang über der Bucht von Palma ist eine der schönsten Arten, das Boot zu nutzen."),
        ],
        "related_labels": ["Ganztag", "Portals Vells", "Preise"],
    },
    "multi-day-charter-balearics": {
        "kicker": "Übernachtung · Balearen",
        "title": "Mehrtages- und Übernachtungscharter — Balearen | Limitless Mallorca",
        "description": "An Bord schlafen und in einer neuen Bucht aufwachen — Mehrtagescharter mit Crew um Mallorca, Menorca, Ibiza und Formentera. 21,5 m Maiora, bis 7 Übernachtungsgäste, transparente APA.",
        "h1": "Mehrtages- und Übernachtungscharter",
        "lead": "Mehr als ein Tag, und Mallorca öffnet sich — Menorca, Ibiza und Formentera rücken in Reichweite. Bei einem Mehrtagescharter schlafen Sie an Bord, wachen irgendwo neu auf und lassen die Reise ihren Rhythmus finden.",
        "sections": [
            (
                "Wohin Sie können",
                'Die wilde Tramuntana-Küste im Nordwesten — <a href="../destinations/west-coast-soller/">Sa Foradada, Sóller und Cala Tuent</a> —, rüber nach <a href="../destinations/ibiza-formentera/">Ibiza und Formentera</a>, das ruhige <a href="../destinations/menorca-crossing/">Menorca</a>, oder die volle Umschiffung Mallorcas in fünf bis sieben Tagen. Über Nacht bis 7 Gäste; die Crew baut jeden Tag um Wetter und Lust.',
            ),
            (
                "Ehrlich bei den Kosten",
                "Längere Reisen laufen über eine APA — Advance Provisioning Allowance, typisch rund 10 % der Chartergebühr — für Verpflegung, extra Kraftstoff und Liegeplatz, mit laufender transparenter Abrechnung durch den Kapitän. Was übrig bleibt, kommt zurück. Wir erklären die Zahlen lieber zu genau, als Sie zu überraschen.",
            ),
        ],
        "cta": "Sagen Sie der Crew Termine und wohin Sie wollen — Sie bekommen eine realistische Route, Meilen und Kostenskizze, nichts zurückgehalten. Siehe <a href=\"../yacht-charter-mallorca-prices/\">Charterpreise</a>.",
        "wa": "Hallo, ich interessiere mich für einen Mehrtagescharter auf der Limitless.",
        "service_name": "Mehrtages-Yachtcharter Balearen — Maiora Limitless",
        "faq": [
            ("Wie viele Gäste schlafen an Bord?", "Über Nacht bis 7."),
            ("Was ist APA?", "Eine Vorauszahlung (rund 10 % der Chartergebühr) für Verpflegung, extra Kraftstoff und Liegeplatz bei Mehrtagen, transparent geführt und am Ende abgerechnet."),
        ],
        "related_labels": ["Reiseziele", "Ibiza & Formentera", "Menorca", "Was inklusive ist"],
    },
    "maiora-yacht-charter": {
        "kicker": "Maiora 21,5 m · Club de Mar",
        "title": "Maiora 21,5 m Yachtcharter Mallorca — „Limitless“ | Mit Crew, 12 Gäste",
        "description": "Chartern Sie die Limitless, eine 21,5 m Maiora-Flybridge-Motoryacht im Club de Mar, Palma. Bis 12 Tages- / 7 Übernachtungsgäste, Crew zu zweit, Seabob, Jet-Tender und Wasserspielzeug.",
        "h1": "Limitless — eine 21,5 m Maiora",
        "lead": "Limitless ist eine Maiora-Flybridge-Motoryacht: 21,5 Meter warmer, gepflegter Raum für genau die Tage, die Mallorca am besten kann. Charterstandard, geführt von einer Crew aus zwei, die das Meer wirklich mögen.",
        "sections": [
            (
                "Für die Küste gebaut",
                "Zwei MTU-Motoren bringen sie bequem auf 16 Knoten Reisegeschwindigkeit, die Buchten sind nie weit. Oben Flybridge und Sonnendeck, achtern Sitzplätze und Outdoor-Bar mit vier Kühlschränken und Eiswürfelbereiter, unten kühle klimatisierte Innenräume. Tagsüber 12 Gäste, über Nacht 7.",
            ),
            (
                "Die Toys",
                "Ein 330-Jet-Tender, Seabob, SUP, Schnorchelsets und Lily Pad; Bose und Sonos, Smart-TVs, Badeleiter und Plattform, damit man mühelos ins Wasser kommt.",
            ),
            (
                "Die Crew",
                "Zwei an Bord, die alles machen — Catering, Beach-Club-Reservierungen, Ankern und die Details. Aufmerksam, erfahren, ein kleines Team, das Anerkennung gleich teilt. Trinkgeld wird nicht erwartet.",
            ),
            (
                "Die Yacht auf einen Blick",
                "Werft: Maiora · Länge: 21,5 m × 5,6 m Breite · Motoren: 2 × MTU, 1.500 PS · Gäste: 12 Tag / 7 Nacht · Crew: 2 · Heimathafen: Club de Mar, Palma de Mallorca. Nicht zu verwechseln mit der 96 m Lürssen gleichen Namens, die manchmal in derselben Marina liegt. Diese Seite ist die Charter-Yacht.",
            ),
        ],
        "cta": "Schreiben Sie Kapitän und Crew, um Termine zu prüfen und ein Angebot zu bekommen. Siehe <a href=\"../yacht-charter-mallorca-prices/\">Charterpreise</a>.",
        "wa": "Hallo, ich interessiere mich für einen Charter der Maiora Limitless.",
        "service_name": "Maiora 21,5 m Limitless Yachtcharter Mallorca",
        "faq": [],
        "related_labels": ["Privater Charter", "Tagescharter", "Preise"],
    },
    "yacht-charter-palma-club-de-mar": {
        "kicker": "Palma · Club de Mar",
        "title": "Yachtcharter Palma de Mallorca — ab Club de Mar | Limitless",
        "description": "Privater Yachtcharter mit Crew ab Club de Mar in Palma de Mallorca. In Minuten von der Stadt an Bord einer 21,5 m Maiora und innerhalb einer Stunde in einer türkisen Bucht.",
        "h1": "Yachtcharter ab Club de Mar, Palma",
        "lead": "Limitless liegt im Club de Mar, einer klassischen Marina Palmas, direkt am Rand der Stadt und der Altstadt. Ein Kaffee in Palma, und kurz danach ankern Sie über türkisem Wasser — die nächsten Buchten sind kaum eine halbe Stunde weg.",
        "sections": [
            (
                "Ein guter Start",
                "Vom Club de Mar liegt die ganze Südwestküste vor der Tür: Portals Vells und die Meereshöhlen, das Meeresschutzgebiet Illes Malgrats, das ruhige Blau von Cala Llamp — alles an einem Vormittag. Andersherum öffnen die weißen Strände der Südküste und der Nationalpark Cabrera für einen Ganztag. Die Crew trifft Sie am Boot und übernimmt.",
            ),
            (
                "Einfach von überall in Palma",
                "Die Marina ist ein kurzes Taxi aus der Stadt, Kreuzfahrtterminal und Flughafen sind nah — ob Sie in Palma wohnen, in Portals oder gerade gelandet sind.",
            ),
        ],
        "cta": "Schicken Sie der Crew Termine und Gruppengröße für Routen ab Club de Mar und ein klares Angebot. Siehe <a href=\"../yacht-charter-mallorca-prices/\">Charterpreise</a>.",
        "wa": "Hallo, ich interessiere mich für einen Charter ab Club de Mar auf der Limitless.",
        "service_name": "Yachtcharter ab Club de Mar Palma — Maiora Limitless",
        "faq": [],
        "related_labels": ["Portals Vells", "Alle Reiseziele", "Tagescharter"],
    },
    "destinations": {
        "kicker": "Routen · Mallorca · Balearen",
        "title": "Wohin die Limitless fährt — Buchten Mallorcas & Balearen | Limitless",
        "description": "Von den türkisen Buchten bei Palma bis Cabrera, Es Trenc, Sa Dragonera und hinüber nach Ibiza, Formentera und Menorca — jede Route an Bord einer 21,5 m Maiora mit Crew.",
        "h1": "Wohin die Limitless Sie bringt",
        "lead": "Jede Route entsteht um Ihre Gruppe — die Ziele unten sind ein Ausgangspunkt, kein festes Menü. Halbtag in den nächsten Buchten, Ganztag die Küste entlang oder Mehrtage zu den Nachbarinseln: Sagen Sie der Crew Termine und Wunsch, Sie bekommen einen realistischen Plan.",
        "sections": [
            (
                "Nah bei Palma — Halbtagsbuchten",
                "Die geschützten türkisen Buchten im Südwesten, an einem Vormittag: Portals Vells und die Meereshöhlen, das Meeresschutzgebiet Illes Malgrats vor El Toro, das tiefe ruhige Blau von Cala Llamp.",
            ),
            (
                "Die Küste entlang — Ganztage",
                "Längere Fahrten bei ruhigem Wetter zu Mallorcas besten Stränden und Schutzgebieten: Sa Dragonera, Cala Pi, Es Trenc, der Nationalpark Cabrera und die fotografierten Buchten im Südosten.",
            ),
            (
                "Über Mallorca hinaus — Mehrtage",
                "An Bord schlafen und weiter kommen: die bergige Nordwestküste, eine volle Umschiffung, und Überfahrten nach Ibiza und Formentera oder das ruhige Menorca.",
            ),
        ],
        "cta": "Schreiben Sie Kapitän und Crew Ihre Termine — sie schlagen die Route vor, die passt.",
        "wa": "Hallo, ich interessiere mich für eine Ziel-Tour auf der Limitless.",
        "service_name": "Yachtcharter-Reiseziele Mallorca",
        "faq": [],
        "related_labels": ["Tagescharter", "Halbtag", "Mehrtage"],
    },
    "yacht-charter-mallorca-prices": {
        "kicker": "Preise · Transparent",
        "title": "Yachtcharter Mallorca Preise — klare Sätze | Limitless",
        "description": "Was ein Yachtcharter mit Crew auf Mallorca kostet: Halbtag ab 1.700 €, Ganztag ab 3.000 €, Crew und MwSt. inklusive. Klare Preise, keine versteckten Extras.",
        "h1": "Yachtcharter Mallorca — Preise",
        "lead": "Wir halten Preise einfach und offen. Unten die Startpreise der Limitless; es sind Richtwerte. Eine kurze Nachricht bringt Ihnen einen genauen Gesamtpreis für Ihre Termine, ohne Extra am Ende.",
        "sections": [
            (
                "Charterpreise",
                "Nebensaison — Halbtag (4h) ab 1.700 € · 6 Stunden ab 2.400 € · Ganztag ab 3.000 €. Hochsaison (Juli–August) — Halbtag (4h) ab 2.200 € · 6 Stunden ab 3.100 € · Ganztag ab 4.000 €. Crew und MwSt. sind in jedem Satz inklusive.",
            ),
            (
                "Was inklusive ist",
                'Ihre Crew aus zwei Personen, Reinigung und MwSt. gehören zum Preis. Ohne Aufpreis an Bord: Seabob, Jet-Tender, SUPs, Schnorchelausrüstung, Sound und Outdoor-Bar. Eine rückzahlbare Kaution (20 %) gilt. Alle Details auf <a href="../what-is-included/">was inklusive ist</a>.',
            ),
            (
                "Was extra ist",
                "Catering und Beach-Club-Reservierungen auf Wunsch. Bei Mehrtagen laufen Verpflegung, Liegeplatz, extra Kraftstoff und die Schlussreinigung über eine transparente APA. Trinkgeld wird nicht erwartet — ganz bei Ihnen.",
            ),
        ],
        "cta": "Schicken Sie Ihre Termine für ein genaues Angebot — vorher klar, ohne Verpflichtung. Siehe <a href=\"../what-is-included/\">was inklusive ist</a> und die <a href=\"../best-time-yacht-charter-mallorca/\">beste Reisezeit</a>.",
        "wa": "Hallo, ich hätte gern ein Angebot für einen Charter auf der Limitless.",
        "service_name": "Yachtcharter Mallorca Preise — Limitless",
        "faq": [
            ("Was kostet ein Tagescharter auf Mallorca?", "Ganztage starten ab 3.000 € in der Nebensaison und 4.000 € im Juli–August, Crew und MwSt. inklusive."),
            ("Gibt es versteckte Kosten?", "Nein. Crew, Reinigung und MwSt. sind inklusive; Catering und Mehrtagskosten stehen vorher transparent."),
        ],
        "related_labels": ["Was inklusive ist", "Beste Reisezeit", "Tagescharter"],
    },
    "what-is-included": {
        "kicker": "So läuft es",
        "title": "Was inklusive ist und wie ein Charter läuft | Limitless Mallorca",
        "description": "Alles, was ein Limitless-Charter enthält, wie der Tag läuft, und klare Antworten zu APA, Kaution und Trinkgeld. Transparenter Yachtcharter mit Crew ab Palma.",
        "h1": "Was inklusive ist — und wie es läuft",
        "lead": "Kein Jargon, keine Überraschungen. Hier steht genau, was Sie bekommen, wie ein Charter läuft, und ehrliche Antworten auf die Fragen, die alle stellen.",
        "sections": [
            (
                "In jedem Charter inklusive",
                "Ihre Crew aus zwei, Reinigung und MwSt.; das volle Wasserspielzeug (Seabob, Jet-Tender, SUPs, Schnorchel, Lily Pad); Sound, Klimaanlage und Outdoor-Bar. Eine rückzahlbare Kaution von 20 % gilt.",
            ),
            (
                "So läuft ein Tag",
                "Sie steigen im Club de Mar zu, die Crew formt die Route nach Ihnen und dem Wetter. Schwimmen, fahren, an Bord essen, Tender an Land — kein Plan außer Ihrem. Catering und Beach Clubs auf Wunsch; die Crew ankert und kümmert sich um die Details.",
            ),
            (
                "APA, erklärt",
                "Bei Mehrtagen deckt eine Advance Provisioning Allowance — typisch rund 10 % der Chartergebühr — Verpflegung, extra Kraftstoff und Liegeplatz. Der Kapitän führt transparent Buch, stockt nur nach, wenn es knapp wird, und gibt den Rest zurück. Tagescharter nutzen keine APA.",
            ),
            (
                "Trinkgeld",
                "Nie inklusive, nie erwartet. Wenn Sie die Crew anerkennen möchten, ganz bei Ihnen — bar, an den Kapitän, gleich im Team geteilt.",
            ),
        ],
        "cta": "Noch eine Frage? Schreiben Sie Kapitän und Crew — sie antworten ehrlich, meist innerhalb von 24 Stunden.",
        "wa": "Hallo, ich habe eine Frage, was bei einem Limitless-Charter inklusive ist.",
        "service_name": "Was inklusive ist — Limitless Yachtcharter",
        "faq": [
            ("Was ist APA?", "Eine Vorauszahlung bei Mehrtagen (rund 10 % der Gebühr) für Verpflegung, Kraftstoff und Liegeplatz, transparent geführt und am Ende abgerechnet."),
            ("Ist Trinkgeld inklusive?", "Nein, und es wird nicht erwartet — ganz bei Ihnen."),
            ("Gibt es eine Kaution?", "Ja, eine rückzahlbare Kaution von 20 %."),
        ],
        "related_labels": ["Preise", "Mehrtage", "Privater Charter"],
    },
    "best-time-yacht-charter-mallorca": {
        "kicker": "Saisonguide",
        "title": "Beste Zeit für Yachtcharter auf Mallorca — Saisonguide | Limitless",
        "description": "Wann chartern auf Mallorca: warmes ruhiges Meer von Mai bis Oktober, stillere Randmonate, Juli–August am lebendigsten. Ein ehrlicher Monatsguide von der Crew.",
        "h1": "Die beste Zeit für einen Charter auf Mallorca",
        "lead": "Mallorca hat eine lange Saison auf dem Wasser. So fühlen sich die Monate vom Deck an — damit Sie die Reise wählen, die zu Ihnen passt. Die Limitless ist das ganze Jahr verfügbar.",
        "sections": [
            (
                "Mai, Juni, September, Oktober — der Sweet Spot",
                "Warmes, ruhiges Meer und weicheres Licht, die Buchten viel stiller als im Hochsommer. Für viele Gäste sind das die besten Monate: das Wasser ist zum Schwimmen, die Ankerplätze haben Platz, längere Fahrten nach Cabrera oder zu den Inseln gehen an ruhigen Tagen leicht. Nebensaisonpreise.",
            ),
            (
                "Juli & August — Hochsommer",
                "Die lebendigsten, wärmsten Monate, die längsten Tage und die vollsten Buchten. Mallorca auf Hochtouren — früh buchen, der Kalender füllt sich schnell, Hochsaisonpreise (Juli–August).",
            ),
            (
                "Zum Wetter",
                "Die Crew formt den Tag immer nach der Vorhersage — wohin Sie an einem Tag fahren, hängt vom Wind ab, und sie steuert Sie zum geschütztesten, schönsten Wasser. Deshalb sind die Routen ein Ausgangspunkt, kein fester Plan.",
            ),
        ],
        "cta": "Sagen Sie der Crew ungefähr, wann Sie kommen wollen — sie sagen ehrlich, was frei ist und wie das Wasser dann ist.",
        "wa": "Hallo, ich möchte die besten Termine für einen Charter auf der Limitless prüfen.",
        "service_name": "Beste Zeit für Yachtcharter Mallorca",
        "faq": [
            ("Wann ist die beste Zeit für einen Charter auf Mallorca?", "Mai, Juni, September und Oktober sind warm, ruhig und stiller; Juli und August am lebendigsten und vollsten."),
            ("Ist die Limitless das ganze Jahr da?", "Ja — ganzjährig, mit Neben- und Hochsaisonpreisen (Juli–August)."),
        ],
        "related_labels": ["Preise", "Tagescharter"],
    },
}

# Destination overlays (same keys as destinations.json slugs).
DEST = {
    "portals-vells": {
        "meta_title": "Portals Vells mit dem Boot — Meereshöhlen & türkise Buchten | Limitless",
        "meta_description": "Charter nach Portals Vells ab Club de Mar — geschützte türkise Buchten und die berühmten Meereshöhlen, nur 35 Minuten von Palma. Maiora mit Crew, bis 12 Gäste.",
        "h1": "Portals Vells — Meereshöhlen und türkise Buchten",
        "tagline": "Die leichte erste Bucht — klares Wasser und kühle Höhlen, kaum eine halbe Stunde von der Marina.",
        "intro": "Zwanzig Minuten hinter den Marinas des Südwestens wird die Küste zu einer Reihe flacher, klarer Buchten. Portals Vells lieben fast alle zuerst: geschützt, sandiger Grund, ruhig, mit den alten Steinhöhlen am Kap.",
        "body": "Es ist der kürzeste Hop — rund 35 Minuten ab Club de Mar — und damit der perfekte Anker für einen Halbtag. Schwimmen von der Plattform ins Wasser, in dem Sie die Zehen sehen, Tender oder SUP zu den Höhlen, die Crew macht den Rest. Weil es so nah ist, gibt es keine Eile.",
        "highlights": ["Eines der klarsten, ruhigsten Wasser nahe Palma", "Die historischen Meereshöhlen am Punkt", "Sandiger Grund, leicht für Kinder", "Nah genug für einen entspannten Halbtag"],
        "coast": "Südwestküste",
    },
    "el-toro-malgrats": {
        "meta_title": "El Toro & Illes Malgrats — Schnorchel-Bootstour | Limitless Mallorca",
        "meta_description": "Charter ins Meeresschutzgebiet Illes Malgrats vor El Toro — das beste Schnorcheln nahe Palma, 40 Minuten ab Club de Mar. Yacht mit Crew, Schnorchel an Bord.",
        "h1": "El Toro & Illes Malgrats — das Schutzgebiet",
        "tagline": "Zwei geschützte Inseln und das beste Schnorcheln in Reichweite von Palma.",
        "intro": "Vor dem Kap El Toro liegen die Illes Malgrats, zwei niedrige Felseninseln in einem Meeresschutzgebiet. Schutz heißt Fische — viele — und Wasser klar genug, um den Grund unter dem Boot verschwinden zu sehen.",
        "body": "Unser Ziel für alle, die unter Wasser etwas sehen wollen. Wir ankern im Lee, verteilen die Schnorchelsets, das Schutzgebiet macht den Rest. Seabob und SUPs kommen hier auch raus. Rund 40 Minuten je Strecke, passt in einen Halbtag, mit Zeit für eine zweite Bucht zum Mittagessen.",
        "highlights": ["Meeresschutzgebiet — reiches, leichtes Schnorcheln", "Geschützter Ankerplatz bei den meisten Bedingungen", "Schnorchel, Seabob und SUP an Bord", "Passt gut zu einer zweiten Bucht"],
        "coast": "Südwestküste",
    },
    "cala-llamp": {
        "meta_title": "Cala Llamp mit dem Boot — geschützt und still | Limitless Yachtcharter",
        "meta_description": "Charter nach Cala Llamp bei Port d'Andratx — eine ruhige, tiefblaue Bucht unter den Klippen, eine Stunde von Palma. Maiora mit Crew, bis 12 Gäste.",
        "h1": "Cala Llamp — geschützt und still",
        "tagline": "Tiefblaues Wasser unter den Klippen bei Port d'Andratx, weg von der Menge.",
        "intro": "Unter den Villen von Port d'Andratx liegt Cala Llamp, die stillere, erwachsenere Bucht des Südwestens — tiefes, stilles Wasser in Tinte und Glas, gerahmt von Pinien und Fels.",
        "body": "Es gibt keinen Strand, und genau das ist der Punkt: Sie schwimmen vom Boot ins Wasser, das ruhig bleibt, wenn es anderswo weht. Beliebt für Gruppen, die die Mitte des Tages still verbringen wollen, rund eine Stunde von der Marina.",
        "highlights": ["Ruhiges, tiefes Wasser, wenn der Südwesten böig ist", "Stiller und privater als die Sandbuchten", "Cliffside-Clubs per Tender", "Ein leichter ganzer Nachmittag oder langer Halbtag"],
        "coast": "Südwestküste",
    },
    "sa-dragonera": {
        "meta_title": "Sa Dragonera & Sant Elm mit dem Boot — Insel-Naturpark | Limitless",
        "meta_description": "Charter nach Sa Dragonera, der unbewohnten Dracheninsel vor Sant Elm — geschützter Naturpark eine Stunde von Palma. Tagescharter mit Crew, bis 12 Gäste.",
        "h1": "Sa Dragonera & Sant Elm — die Dracheninsel",
        "tagline": "Ein unbewohnter Inselpark an der Westspitze Mallorcas, Klippen und klare Rinnen.",
        "intro": "Sa Dragonera liegt vor der Westspitze wie ein schlafender Drache — unbewohnt, geschützt, wilder als die vollen Südbuchten. Der enge Kanal zur Insel hält eines der klarsten Wasser Mallorcas.",
        "body": "Als Naturpark nur Bojen, deshalb still und sauber. Wir machen einen Ganztag daraus: die Küste hoch, Boje im Kanal, schwimmen und schnorcheln, Tender nach Sant Elm zum Mittagessen oder an Bord mit Blick auf die Insel. Etwa eine Stunde zehn je Strecke.",
        "highlights": ["Geschützter Naturpark — wirklich wild", "Außergewöhnlich klares Wasser im Kanal", "Sant Elm per Tender zum Mittagessen", "Ein richtiger Ganztag die Westküste hoch"],
        "coast": "Westküste",
    },
    "cala-pi": {
        "meta_title": "Cala Pi mit dem Boot — Klippen und feiner Sand | Limitless",
        "meta_description": "Charter nach Cala Pi an Mallorcas Südküste — ein dramatischer Kliff-Einschnitt mit feinem Sand, eine Stunde von Palma. Maiora-Tagescharter mit Crew.",
        "h1": "Cala Pi — geschützte Klippen und feiner Sand",
        "tagline": "Ein dramatischer schmaler Einschnitt tief in die Südküste.",
        "intro": "Cala Pi ist ein echter versteckter Einschnitt — ein schmaler Schlitz in den Südküstenklippen, der auf einen Keil feinen, hellen Sands und türkises Flachwasser öffnet. Vom Wasser eindrucksvoller als jedes Foto von oben.",
        "body": "Die Klippen geben echten Schutz, der flache sandige Eingang macht das Wasser unwirklich blau. Wir ankern vor der Mündung, schwimmen zum Strand. Rund eine Stunde fünf je Strecke — ein ruhiger Ganztag an der stilleren Südküste.",
        "highlights": ["Dramatischer Kliff-Einschnitt, am besten vom Meer", "Feiner Sand und helles Türkis", "Gut geschützt vor den meisten Sommerwinden", "Stillere Alternative zum vollen Südwesten"],
        "coast": "Südküste",
    },
    "es-trenc": {
        "meta_title": "Es Trenc mit dem Boot — karibisch-weißer Sand | Limitless Yachtcharter",
        "meta_description": "Charter nach Es Trenc — Mallorcas längster wilder weißer Strand und sein berühmtes Türkis, mit der Yacht von Palma. Maiora mit Crew, bis 12 Gäste.",
        "h1": "Es Trenc — Mallorcas karibisch-weißer Sand",
        "tagline": "Der berühmteste wilde weiße Sand der Insel und unwirkliches Türkis.",
        "intro": "Es Trenc ist das Bild, das die Leute von Mallorca haben — eine lange, unbebauten Reihe karibisch-weißen Sands hinter Dünen, flaches Wasser in jeder Türkis- und Jadestufe.",
        "body": "Weil gebaut nicht werden darf, bleibt der Strand wild, und das Beste erreicht man bequem nur mit dem Boot. Wir ankern vor dem Sand im Flachen, die Gruppe treibt, schwimmt und paddelt so weit sie will. Rund eineinhalb Stunden je Strecke — ein klassischer Ganztag die Südküste runter.",
        "highlights": ["Mallorcas berühmtester weißer Strand", "Flaches, warmes, endlos türkises Wasser", "Wild und unbebaut — am besten vom Wasser", "Ein Signature-Ganztagescharter"],
        "coast": "Südküste",
    },
    "cabrera": {
        "meta_title": "Yachtcharter zum Nationalpark Cabrera | Limitless Mallorca",
        "meta_description": "Charter nach Cabrera, Mallorcas geschütztem marinen Nationalpark — türkise Buchten, die Blaue Höhle und reiches Meer. Genehmigung vorhanden. Maiora-Tagescharter ab Palma.",
        "h1": "Nationalpark Cabrera mit der Yacht",
        "tagline": "Mallorcas geschützter Archipel — ein mariner Nationalpark, den die meisten nie erreichen.",
        "intro": "Südlich von Mallorca, hinter den letzten Buchten, liegt Cabrera: ein kleiner Archipel als Land- und Meeresnationalpark. Zugang begrenzt und genehmigungspflichtig — deshalb so unberührt.",
        "body": "Wir haben die Genehmigung, der Papierkram ist unserer, nicht Ihrer. Der Tag baut auf die Überfahrt — rund eine Stunde vierzig je Strecke — und belohnt mit einem geschützten Ankerplatz, der Blauen Höhle per Tender und Schnorcheln, das zeigt, warum der Park existiert. Ein langer, merkwürdiger Ganztag; bei ruhigem Wetter eines der Besten von Palma. Früh schreiben, die Bojen sind begrenzt.",
        "highlights": ["Geschützter mariner Nationalpark — wirklich selten", "Genehmigung bei uns — kein Aufwand für Sie", "Die Blaue Höhle und makelloses Schnorcheln", "Einer der großen Ganztage ab Palma"],
        "coast": "Südlicher Archipel",
    },
    "calo-des-moro": {
        "meta_title": "Caló des Moro mit dem Boot — Mallorcas meistfotografierte Bucht | Limitless",
        "meta_description": "Charter nach Caló des Moro und Cala Figuera an Mallorcas Südostküste — die meistfotografierte Bucht der Insel, am besten vom Wasser. Maiora mit Crew.",
        "h1": "Caló des Moro & Cala Figuera — die fotografierten Buchten",
        "tagline": "Die meistfotografierte Bucht Mallorcas — und vom Wasser viel besser als von der Schlange auf der Klippe.",
        "intro": "Caló des Moro ist die winzige, perfekte Bucht, die Sie hundertmal online gesehen haben: eine Schaufel weißen Sands zwischen steilen Pinienklippen, Wasser wie ein Pool. Von oben heißt das Klettern und Menge. Vom Meer schwimmen Sie hinein.",
        "body": "Das benachbarte Cala Figuera ist ebenso schön und stiller. Eine längere Fahrt — rund zwei Stunden zehn je Strecke in die Südostecke — also ein früher Ganztag, der sich lohnt. Wir ankern vor der Bucht, schwimmen an den Klippen vorbei. Am besten an ruhigen Tagen; die Crew steuert nach der Vorhersage.",
        "highlights": ["Mallorcas meistfotografierte Bucht, vom Meer", "Stillere Nachbarin Cala Figuera daneben", "Kein Kliff-Aufstieg, keine Menge", "Ein lohnender langer Ganztag nach Südosten"],
        "coast": "Südostküste",
    },
    "west-coast-soller": {
        "meta_title": "Nordwestküste Yachtcharter — Sa Foradada, Sóller, Cala Tuent | Limitless",
        "meta_description": "Mallorcas dramatische Tramuntana-Küste mit der Yacht — Sa Foradada, Port de Sóller und Cala Tuent unter den Bergen. Mehrtagescharter mit Crew ab Palma.",
        "h1": "Die Nordwestküste — Berge treffen das Meer",
        "tagline": "Die wilde Tramuntana-Seite der Insel — Klippen, Bergdörfer und tiefes, kaltblaues Wasser.",
        "intro": "Der Nordwesten ist das Mallorca, das die meisten Tagescharter nie sehen: die Serra de Tramuntana fällt ins Meer, der durchlöcherte Fels von Sa Foradada, der Hafen von Port de Sóller und die abgelegene Kiesbucht Cala Tuent unter den höchsten Gipfeln.",
        "body": "Zu weit und zu gut, um zu hetzen — wir behandeln es als Übernachtung oder Mehrtage, nicht als Sprint. Ankern unter Sa Foradada zum Mittagessen, Boje in Sóllers runder Bucht am Abend, aufwachen irgendwo spektakulär. Die Crew legt Ankerplätze, Meilen und laufende Kosten ehrlich für Ihre Termine.",
        "highlights": ["Die dramatische Tramuntana-Küste", "Sa Foradada, Port de Sóller und Cala Tuent", "Am besten als Übernachtung oder Mehrtage", "Landschaft in ganz anderem Maßstab"],
        "coast": "Nordwestküste",
    },
    "mallorca-circumnavigation": {
        "meta_title": "Um Mallorca segeln — volle Inselumrundung mit der Yacht | Limitless",
        "meta_description": "Mallorca mit der privaten Yacht umrunden — die komplette 200-sm-Schleife in 5–7 Tagen, Buchten, Berge und stille Ankerplätze. Maiora mit Crew, bis 7 Übernachtungsgäste.",
        "h1": "Um Mallorca — die volle Inselumrundung",
        "tagline": "Die ganze Insel, Küste für Küste, in Ihrem Tempo über mehrere Tage.",
        "intro": "Mallorca ist vielfältiger, als ein Tag zeigen kann: das Türkis im Süden, die wilde Tramuntana im Nordwesten, die stillen Buchten im Osten. Die Umschiffung fädelt sie zu einer unhurrierten Schleife.",
        "body": "Rund 200 Seemeilen — etwa zwölfeinhalb Stunden echte Fahrt — deshalb empfehlen wir fünf bis sieben Tage, an Bord schlafen, jeden Morgen eine neue Bucht. Sie setzen das Tempo; die Crew formt jeden Tag um Wetter und Lust. Verpflegung, Liegeplatz und Kraftstoff über eine APA mit laufender Abrechnung. Der beste Weg, die ganze Insel zu sehen.",
        "highlights": ["Jede Küste Mallorcas in einer Reise", "5–7 Tage, an Bord schlafen, neue Bucht jeden Morgen", "Ganz Ihr Tempo und Ihre Route", "Transparente APA — laufende Kosten offen"],
        "coast": "Ganze Insel",
    },
    "ibiza-formentera": {
        "meta_title": "Yachtcharter nach Ibiza & Formentera von Mallorca | Limitless",
        "meta_description": "Von Mallorca nach Ibiza und Formentera mit der privaten Yacht — die weiße Insel und Formenteras türkise Sandbänke. Mehrtagescharter mit Crew, bis 7 Übernachtungsgäste.",
        "h1": "Ibiza & Formentera — die Überfahrt zur weißen Insel",
        "tagline": "Hinüber zu den Pityusen — Ibizas Energie und Formenteras karibische Sandbänke.",
        "intro": "Westlich von Mallorca liegen Ibiza und dahinter Formentera. Ibiza für Glamour, Ankerplätze und Abende; Formentera für Wasser so flach und klar über weißem Sand, dass es tropisch wirkt.",
        "body": "Die Überfahrt ist rund viereinhalb Stunden, also fest ein Mehrtages-Trip: bei ruhigem Wetter rüber, Tage auf Formenteras Sandbänken, Abende vor Ibiza, zurück wenn der Wind stimmt. Marina oder Anker, je nach Gruppe. Die Crew legt Distanzen, Kraftstoff, Liegeplatz und APA klar für Ihre Termine — nichts zurückgehalten.",
        "highlights": ["Formenteras berühmte türkise Sandbänke", "Ibizas Ankerplätze und Abende", "Eine Mehrtages-Überfahrt bei ruhigem Wetter", "Marina oder Anker — Ihre Wahl"],
        "coast": "Balearen-Überfahrt",
    },
    "menorca-crossing": {
        "meta_title": "Yachtcharter nach Menorca von Mallorca | Limitless",
        "meta_description": "Nach Menorca mit der privaten Yacht — wilde unberührte Buchten und der große Naturhafen von Maó. Mehrtagescharter mit Crew ab Mallorca, bis 7 Übernachtungsgäste.",
        "h1": "Menorca — die wilde, unberührte Überfahrt",
        "tagline": "Die stille Baleareninsel — unberührte Buchten und einer der großen Naturhäfen der Welt.",
        "intro": "Menorca ist die Baleareninsel, die die Zeit vergessen hat, im besten Sinn: ein Biosphärenreservat unbebauter Buchten, heller Sand und prähistorische Ufer, weit weniger Boote als die lauteren Nachbarn.",
        "body": "Die Überfahrt ist etwas unter vier Stunden — ein lohnender Mehrtages-Ausbruch für Gäste, die wirklich Ruhe wollen. Die Südküste entlang der wilden Calas, in den weiten Naturhafen von Maó, schwimmen in Wasser, das selbst im August leer bleibt. Distanzen, Kraftstoff, Liegeplatz und APA ehrlich für Ihre Termine.",
        "highlights": ["Menorcas wilde, unbebaute Südküsten-Calas", "Der große Naturhafen von Maó", "Viel stiller als Ibiza oder die Mallorca-Buchten", "Eine entspannte Mehrtages-Überfahrt"],
        "coast": "Balearen-Überfahrt",
    },
}
